apiVersion: v1
kind: Service
metadata:
  name: oais-platform
  labels:
    run: oais-platform
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: oais-platform
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oais-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oais-platform
  template:
    metadata:
      labels:
        app: oais-platform
      annotations:
      {{- include "oais.env-checksum" . | indent 8 }}
      {{- include "oais.config-checksum" . | indent 8 }}
    spec:
      containers:
        - name: oais-platform
          image: {{ .Values.oais.image }}
          command: ["sh"]
          args: ["-c", "python3 manage.py migrate &&
            python3 manage.py collectstatic --no-input &&
            cp -R /assets/. /shared-assets &&
            cp -R /tmp/assets/. /shared-assets &&
            python3 manage.py runserver 0.0.0.0:8000"]
          envFrom:
            - configMapRef:
                name: env
            - secretRef:
                name: oais-secrets
          ports:
            - containerPort: 8000
          volumeMounts:
            - mountPath: /shared-assets
              name: shared-assets
            - mountPath: /oais-platform/oais_platform/local_settings
              name: oais-platform-config
              readOnly: true
          imagePullPolicy: Always

        - name: nginx
          image: nginx
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /shared-assets
              name: shared-assets
              readOnly: true
            - mountPath: /etc/nginx/conf.d
              name: nginx-config
              readOnly: true
            - mountPath: /var/cache/nginx
              name: nginx-cache
            - mountPath: /var/run
              name: var-run

      volumes:
        - name: shared-assets
          emptyDir: {}
        - name: oais-platform-config
          configMap:
            name: oais-platform-config
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: nginx-cache
          emptyDir: {}
        - name: var-run
          emptyDir: {}
      restartPolicy: Always
