apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: oais-platform-route
spec:
  host: {{ .Values.oais.hostname }}
  to:
    kind: Service
    name: oais-platform
    weight: 1
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
status:
    ingress: []