oais:
  checkHostname: true
  hostname: preserve-qa.web.cern.ch
  image: gitlab-registry.cern.ch/digitalmemory/openshift-deploy/oais_dev:latest
  sipPath: /eos/user/o/oais/platform-storage/preserve-qa/sips
  aipPath: /eos/user/o/oais/platform-storage/preserve-qa/aips

archivematica:
  archivematica_url: https://preserve-qa-am.web.cern.ch
  am_abs_directory: /eos/user/o/oais/platform-storage/preserve-qa/sips
  am_rel_directory: /
  am_username: archivematica
  am_ss_url: https://preserve-qa-am-ss.web.cern.ch
  am_ss_username: archivematica_ss
  am_transfer_source_uuid: 7cd37e2e-dd55-4449-937d-93f4b67e377a

inveniordm:
  baseUrl: https://188.185.38.21:5000

oidc:
  clientId: preserve-qa

redis:
  persistence:
    enabled: true
    size: 2Gi

postgres:
  db: oais_db
  user: oais
  persistence:
    enabled: true
    size: 5Gi

route:
  enabled: true
  tls: true
