oais:
  checkHostname: true
  hostname: dm-luteus.web.cern.ch
  image: gitlab-registry.cern.ch/digitalmemory/openshift-deploy/oais_dev:latest
  sipPath: /eos/user/o/oais/platform-storage/luteus/sips

oidc:
  clientId: dm-luteus

redis:
  persistence:
    enabled: true
    size: 2Gi

postgres:
  db: oais_db
  user: oais
  persistence:
    enabled: true
    size: 5Gi

route:
  enabled: true
  tls: true
