oais:
  hostname: test-dm-openshift.web.cern.ch
  image: gitlab-registry.cern.ch/digitalmemory/openshift-deploy/oais:latest

oidc:
  clientId: dm-test

redis:
  storage: 2Gi
  storageClassName: cephfs

postgres:
  db: oais_db
  user: oais
  storage: 5Gi
  storageClassName: cephfs