# EXAMPLE values to deploy the oais-platform

oais:
  checkHostname: true
  hostname: dm-luteus.web.cern.ch
  image: gitlab-registry.cern.ch/digitalmemory/openshift-deploy/oais_dev:latest
  sipPath: /path-to-sip
  aipPath: /path-to-aip

archivematica:
  archivematica_url: https://dashboard-url.com
  am_abs_directory: /path-to-sip
  am_rel_directory: /path-to-sip
  am_username: archivematica
  am_ss_url: https://storage-service-url.com
  am_ss_username: archivematica
  am_transfer_source_uuid: transfer-uuid

fts:
  instance: https://fts3-pilot.cern.ch:8446

cta:
  base_path: root://eosctapublicpps.cern.ch//eos/ctapublicpps/archivetest/digital-memory/

inveniordm:
  baseUrl: your-invenio-url

oidc:
  clientId: dm-luteus

redis:
  persistence:
    enabled: true
    size: 2Gi

postgres:
  db: oais_db
  user: oais
  persistence:
    enabled: true
    size: 5Gi

route:
  enabled: true
  tls: true
