oais:
  checkHostname: true
  hostname: test-dm-openshift.web.cern.ch
  image: gitlab-registry.cern.ch/digitalmemory/openshift-deploy/oais:latest

oidc:
  clientId: dm-test

redis:
  persistence:
    enabled: true
    size: 2Gi
    storageClass: cephfs

postgres:
  db: oais_db
  user: oais
  persistence:
    enabled: true
    size: 5Gi
    storageClass: cephfs

route:
  enabled: true
  tls: true
